# Generated by Django 2.2 on 2022-01-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('posted_by', models.CharField(choices=[('Agent', 'Agent'), ('Land lord', 'Land lord'), ('Tenant', 'tenant')], default='Landlord', max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('rent', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('image_2', models.ImageField(default='houses', upload_to='houses')),
                ('image_3', models.ImageField(default='houses', upload_to='houses')),
                ('image_1', models.ImageField(default='houses', upload_to='houses')),
                ('image_4', models.ImageField(default='houses', upload_to='houses')),
                ('image_5', models.ImageField(default='houses', upload_to='houses')),
                ('image_6', models.ImageField(default='houses', upload_to='houses')),
                ('image_7', models.ImageField(default='houses', upload_to='houses')),
                ('image_8', models.ImageField(default='houses', upload_to='houses')),
                ('image_9', models.ImageField(default='houses', upload_to='houses')),
                ('image_10', models.ImageField(default='houses', upload_to='houses')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwapHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('swap_house_option', models.CharField(choices=[('Swapwith another house', 'Swap with another house'), ('Swap for with Discounted Deposit', 'Swap for with Discounted Deposit'), ('Swap for another house/Discounted Deposit', 'Swap for another house/Discounted Deposit')], default='swap house', max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('rent', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('image_1', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_2', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_3', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_4', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_5', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_6', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_7', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_8', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_9', models.ImageField(default='image', upload_to='swap-houses')),
                ('image_10', models.ImageField(default='image', upload_to='swap-houses')),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('land', 'land')], default='property type', max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('image_2', models.ImageField(default='property', upload_to='property')),
                ('image_3', models.ImageField(default='property', upload_to='property')),
                ('image_1', models.ImageField(default='property', upload_to='property')),
                ('image_4', models.ImageField(default='property', upload_to='property')),
                ('image_5', models.ImageField(default='property', upload_to='property')),
                ('image_6', models.ImageField(default='property', upload_to='property')),
                ('image_7', models.ImageField(default='property', upload_to='property')),
                ('image_8', models.ImageField(default='property', upload_to='property')),
                ('image_9', models.ImageField(default='property', upload_to='property')),
                ('image_10', models.ImageField(default='property', upload_to='property')),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('date_send', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('date_replied', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.House')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Member'),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
