# Generated by Django 2.2 on 2022-01-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('booking_option', models.CharField(choices=[('Half Day', 'Half Day'), ('Full Day', 'Full Day')], default='Half Day', max_length=200)),
                ('rooms_count', models.IntegerField()),
                ('room_type', models.CharField(choices=[('hotel', 'hotel'), ('apartment', 'apartment'), ('Guest house', 'Guest house')], default='Hotel', max_length=200)),
                ('available_rooms', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('beds_count', models.IntegerField(default=0)),
                ('bathroom', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], default='Indoor', max_length=200)),
                ('swimming_pool', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('wifi', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('gym', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('restaurant', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('balcony', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('bar', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('lift_or_ramp', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('kitchen', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('netflix', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('house_keeper', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200)),
                ('image_1', models.ImageField(default='image', upload_to='hotel')),
                ('image_2', models.ImageField(default='image', upload_to='hotel')),
                ('image_3', models.ImageField(default='image', upload_to='hotel')),
                ('image_4', models.ImageField(default='image', upload_to='hotel')),
                ('image_5', models.ImageField(default='image', upload_to='hotel')),
                ('image_6', models.ImageField(default='image', upload_to='hotel')),
                ('image_7', models.ImageField(default='image', upload_to='hotel')),
                ('image_8', models.ImageField(default='image', upload_to='hotel')),
                ('image_9', models.ImageField(default='image', upload_to='hotel')),
                ('image_10', models.ImageField(default='image', upload_to='hotel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_option', models.CharField(choices=[('Half Day', 'Half Day'), ('Full Day', 'Full Day')], default='Half Day', max_length=200)),
                ('rooms_booked', models.IntegerField()),
                ('date_booked', models.DateField()),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
