# Generated by Django 4.0.2 on 2022-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_1',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_10',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_2',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_3',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_4',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_5',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_6',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_7',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_8',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_9',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='hotel'),
        ),
    ]
