# Generated by Django 4.0.2 on 2022-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_id_alter_hotel_id_alter_hotel_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
