# Generated by Django 4.0.2 on 2022-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_booking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(auto_now=True),
        ),
    ]
