# Generated by Django 4.0.2 on 2022-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_booking_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(null=True),
        ),
    ]
